version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./Ex2:/usr/share/nginx/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:7.4-fpm
    volumes:
      - ./Ex2:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
